name: create-doubtfire-deployment
on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - '*.x'
    #   - 'development'
    #   - 'main'
  # deployment:
  # workflow_dispatch:
jobs:
  docker-deploy-development-image:
    if: github.repository_owner == 'doubtfire-lms'
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for development image
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: lmsdoubtfire/doubtfire-web
          tags: |
            type=semver,pattern={{major}}.{{minor}}.x-dev
      - name: Build and push web server
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-web-server:
    if: github.repository_owner == 'doubtfire-lms'
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for web server
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: lmsdoubtfire/doubtfire-web
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern=prod-{{version}}
            type=semver,pattern=prod-{{major}}.{{minor}}
            type=semver,pattern=prod-{{major}}
      - name: Build and push web server
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: deploy.Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
